import type { SectionId, Values } from "./types";

/**
 * Command table for the toolkit, kept separate from the tool definitions so
 * activation only registers command ids: the definitions and their engines
 * load when a tool is first opened. A unit test keeps this list in step with
 * the registry.
 */
export interface ToolkitCommand {
  command: string;
  tool: string;
  section: SectionId;
  title: string;
  /** Preset values for alias commands (e.g. URL mode of the encoder). */
  values?: Values;
}

export const TOOLKIT_COMMANDS: ToolkitCommand[] = [
  { command: "curlConverter", tool: "web.curl", section: "api", title: "cURL Converter" },
  { command: "apiResponseInspector", tool: "web.api-response", section: "api", title: "API Response Inspector" },
  { command: "urlTools", tool: "web.url", section: "api", title: "URL & Query String Tool" },
  { command: "corsHelper", tool: "web.cors", section: "api", title: "CORS Builder & Debugger" },
  { command: "openApiTools", tool: "web.openapi", section: "api", title: "OpenAPI / Swagger Toolkit" },
  { command: "graphqlTools", tool: "web.graphql", section: "api", title: "GraphQL Formatter & Types" },
  { command: "apiScaffolder", tool: "web.api-scaffold", section: "api", title: "API Resource Scaffolder" },
  { command: "reactGenerator", tool: "web.react", section: "frontend", title: "React / Next.js Generator" },
  { command: "htmlToJsx", tool: "web.html-jsx", section: "frontend", title: "HTML → JSX Converter" },
  { command: "cssUnits", tool: "web.css-units", section: "frontend", title: "CSS Units & Fluid Type" },
  { command: "colorConverter", tool: "mobile.colors", section: "frontend", title: "Color Converter & Palette" },
  { command: "colorPalette", tool: "mobile.colors", section: "frontend", title: "Color Converter & Palette", values: {} },
  { command: "metaTagsGenerator", tool: "web.meta", section: "frontend", title: "SEO & Social Meta Tags" },
  { command: "cacheControl", tool: "web.cache", section: "frontend", title: "Cache-Control Builder" },
  { command: "deviceCommands", tool: "mobile.devices", section: "mobile", title: "adb & simctl Command Builder" },
  { command: "deepLinkHelper", tool: "mobile.deep-links", section: "mobile", title: "Deep Links & Universal Links" },
  { command: "appPermissions", tool: "mobile.permissions", section: "mobile", title: "App Permissions Generator" },
  { command: "mobileLocalApi", tool: "mobile.local-api", section: "mobile", title: "Local API Access from Devices" },
  { command: "appEnvironments", tool: "mobile.environments", section: "mobile", title: "Environments & Build Flavors" },
  { command: "appSigning", tool: "mobile.signing", section: "mobile", title: "Signing, Keystores & Fingerprints" },
  { command: "sdkVersions", tool: "mobile.versions", section: "mobile", title: "SDK & Build Compatibility" },
  { command: "mobileCiGenerator", tool: "mobile.ci", section: "mobile", title: "Mobile CI Workflow" },
  { command: "densityConverter", tool: "mobile.density", section: "mobile", title: "dp / px / pt Converter & Asset Sizes" },
  { command: "jsonFormatter", tool: "text.format", section: "text", title: "JSON / YAML / XML Formatter" },
  { command: "yamlJsonTool", tool: "text.format", section: "text", title: "JSON / YAML / XML Formatter", values: {"format":"auto","action":"validate"} },
  { command: "textDiff", tool: "dev.diff", section: "text", title: "Diff Checker" },
  { command: "regexLibrary", tool: "dev.regex-library", section: "text", title: "Regex Tester, Library & Code" },
  { command: "regexBuilder", tool: "dev.regex-library", section: "text", title: "Regex Tester, Library & Code", values: {"preset":"custom","perLine":false} },
  { command: "caseConverter", tool: "dev.text", section: "text", title: "Case Converter & Text Tools" },
  { command: "base64Encoder", tool: "dev.encode", section: "convert", title: "Encode / Decode" },
  { command: "urlEncoder", tool: "dev.encode", section: "convert", title: "Encode / Decode", values: {"codec":"url-component","direction":"auto"} },
  { command: "timestampConverter", tool: "dev.timestamp", section: "convert", title: "Timestamp Converter" },
  { command: "idGenerator", tool: "dev.ids", section: "convert", title: "UUID & ID Generator" },
  { command: "jsonToTypes", tool: "data.types", section: "convert", title: "JSON to Types" },
  { command: "dataConverter", tool: "data.convert", section: "convert", title: "Data Converter" },
  { command: "sparkSqlFormatter", tool: "data.sql", section: "database", title: "SQL Formatter & Linter" },
  { command: "sqlQueryHelper", tool: "data.sql-helper", section: "database", title: "SQL Query Helper" },
  { command: "connectionString", tool: "web.db-url", section: "database", title: "Database Connection Strings" },
  { command: "sqlToMongo", tool: "web.sql-mongo", section: "database", title: "SQL → MongoDB Query" },
  { command: "buildErrorExplainer", tool: "mobile.build-errors", section: "testing", title: "Build Error Explainer" },
  { command: "observabilityAnalyze", tool: "devops.logs", section: "testing", title: "Log Analyzer & Formatter" },
  { command: "mockDataGenerator", tool: "data.mock", section: "testing", title: "Mock Data Generator" },
  { command: "jsonSchemaValidator", tool: "data.schema-validate", section: "testing", title: "JSON Schema Validator" },
  { command: "networkTools", tool: "devops.network", section: "testing", title: "Port & Network Toolkit" },
  { command: "gitRecipes", tool: "web.git", section: "git", title: "Git Command Recipes" },
  { command: "gitignoreGenerator", tool: "web.gitignore", section: "git", title: ".gitignore Generator" },
  { command: "semverCalculator", tool: "web.semver", section: "git", title: "Semver & App Version Calculator" },
  { command: "dockerfileHelper", tool: "devops.dockerfile", section: "devops", title: "Dockerfile Generator & Linter" },
  { command: "composeHelper", tool: "devops.compose", section: "devops", title: "Docker Compose Generator & Validator" },
  { command: "dockerRunToCompose", tool: "devops.docker-run", section: "devops", title: "docker run → Compose" },
  { command: "ciPipelineGenerator", tool: "devops.ci", section: "devops", title: "CI Pipeline Generator" },
  { command: "envChecker", tool: "devops.env", section: "devops", title: ".env Checker & Generator" },
  { command: "kubernetesHelper", tool: "devops.k8s", section: "devops", title: "Kubernetes & Helm Generator / Validator" },
  { command: "cloudDeployGenerator", tool: "devops.deploy", section: "devops", title: "Cloud Deploy Workflow" },
  { command: "cronHelper", tool: "dev.cron", section: "devops", title: "Cron Expression Helper" },
  { command: "nginxConfig", tool: "devops.nginx", section: "devops", title: "Nginx Config Generator" },
  { command: "healthCheckGenerator", tool: "devops.health", section: "devops", title: "Health Check Generator" },
  { command: "terraformGenerator", tool: "devops.terraform", section: "devops", title: "Terraform Starter" },
  { command: "pm2Config", tool: "devops.pm2", section: "devops", title: "PM2 Ecosystem Generator" },
  { command: "observabilityStarter", tool: "devops.observability", section: "devops", title: "Observability Starter" },
  { command: "jwtDecoder", tool: "dev.jwt", section: "security", title: "JWT Decoder & Signer" },
  { command: "hashGenerator", tool: "dev.hash", section: "security", title: "Hash, HMAC & Webhook Signatures" },
  { command: "oauthPkce", tool: "web.oauth", section: "security", title: "OAuth 2.0 & PKCE Helper" },
  { command: "securityHeaders", tool: "web.security-headers", section: "security", title: "CSP & Security Headers" },
  { command: "cookieInspector", tool: "web.cookies", section: "security", title: "Cookie Inspector & Builder" },
  { command: "certInspector", tool: "mobile.certificates", section: "security", title: "Certificate & SSL Pinning Inspector" },
  { command: "promptTemplate", tool: "ai.prompt-builder", section: "ai", title: "Prompt Builder" },
  { command: "tokenCounter", tool: "ai.token-cost", section: "ai", title: "LLM Models, Tokens & Cost" },
  { command: "modelComparison", tool: "ai.token-cost", section: "ai", title: "LLM Models, Tokens & Cost", values: {"mode":"compare"} },
  { command: "llmClientSetup", tool: "ai.llm-config", section: "ai", title: "LLM Client Setup" },
  { command: "llmJsonValidator", tool: "ai.json-output", section: "ai", title: "LLM Output Cleaner & JSON Validator" },
  { command: "llmResponseFormatter", tool: "ai.json-output", section: "ai", title: "LLM Output Cleaner & JSON Validator", values: {"mode":"clean"} },
  { command: "llmApiTester", tool: "ai.llm-tester", section: "ai", title: "LLM API Tester" },
  { command: "jsonToToon", tool: "ai.toon", section: "ai", title: "JSON → TOON for Prompts" },
  { command: "aiAppStarter", tool: "ai.project", section: "ai", title: "AI App Starter" },
  { command: "mlCodeGen", tool: "ai.snippets", section: "ai", title: "AI/ML Code Snippets" },
  { command: "gpuVram", tool: "ai.vram", section: "ai", title: "GPU Memory & Speed Estimator" },
  { command: "mlopsGenerator", tool: "devops.serving", section: "ai", title: "Model Serving Starter" },
  { command: "metricsCalculator", tool: "ai.metrics", section: "ai", title: "Model Metrics" },
  { command: "datasetSplit", tool: "ai.dataset-split", section: "ai", title: "Dataset Split Planner" },
  { command: "lrScheduler", tool: "ai.lr-schedule", section: "ai", title: "Learning-Rate Schedule" },
  { command: "modelCard", tool: "ai.model-card", section: "ai", title: "Model Card" },
  { command: "chunkingTester", tool: "rag.chunker", section: "data", title: "Chunking Tester" },
  { command: "ragPipeline", tool: "rag.pipeline", section: "data", title: "RAG Pipeline Generator" },
  { command: "vectorStoreSetup", tool: "rag.vector-store", section: "data", title: "Vector Store Setup" },
  { command: "embeddingModelGuide", tool: "rag.embedding-models", section: "data", title: "Embedding Model Guide" },
  { command: "retrievalConfig", tool: "rag.retrieval", section: "data", title: "Retrieval Configuration" },
  { command: "contextWindow", tool: "rag.context-budget", section: "data", title: "Context Window Budget" },
  { command: "ragPromptBuilder", tool: "rag.prompt", section: "data", title: "Grounded Prompt Assembler" },
  { command: "embeddingCost", tool: "rag.ingestion-plan", section: "data", title: "Chunk & Index Size Calculator" },
  { command: "ragEvalScores", tool: "rag.retrieval-eval", section: "data", title: "Retrieval Evaluation" },
  { command: "ragHallucinationAnalyzer", tool: "rag.grounding", section: "data", title: "Answer Grounding Checker" },
  { command: "vectorSimilarity", tool: "ai.vector-similarity", section: "data", title: "Vector Similarity" },
  { command: "semanticDedup", tool: "rag.dedup", section: "data", title: "Near-Duplicate Chunk Finder" },
  { command: "hybridSearchRrf", tool: "rag.rrf", section: "data", title: "Hybrid Search Fusion (RRF)" },
  { command: "chunkMetadataValidator", tool: "rag.metadata", section: "data", title: "Chunk Metadata Validator" },
  { command: "dataTransform", tool: "data.transform", section: "data", title: "Data Transformer" },
  { command: "dataQualityChecker", tool: "data.profile", section: "data", title: "Data Profiler & Quality Check" },
  { command: "jsonlViewer", tool: "data.jsonl", section: "data", title: "JSON Lines Inspector" },
  { command: "schemaViewer", tool: "data.schema", section: "data", title: "Schema Viewer & Diff" },
  { command: "schemaDiff", tool: "data.schema", section: "data", title: "Schema Viewer & Diff", values: {"mode":"diff"} },
  { command: "partitionCalc", tool: "data.partitions", section: "data", title: "Partition & File Size Planner" },
  { command: "sparkCostEstimator", tool: "data.spark-cluster", section: "data", title: "Spark Cluster & Cost Estimator" },
  { command: "deltaLakeAnalyzer", tool: "data.delta-log", section: "data", title: "Delta Lake Log Analyzer" },
];
