/**
 * Client setup code for LLM providers: SDK install, environment variables and
 * a minimal, production-shaped call (timeout, retries, optional streaming).
 * Keys are always read from the environment - generated code never contains one.
 */

export type LlmProvider = "openai" | "anthropic" | "gemini" | "azure-openai" | "ollama" | "openai-compatible";
export type LlmLanguage = "python" | "typescript" | "curl";

export interface LlmConfigOptions {
  provider: LlmProvider;
  language: LlmLanguage;
  model: string;
  stream: boolean;
  temperature: number;
  timeoutSeconds: number;
  maxRetries: number;
  baseUrl?: string;
}

export const LLM_PROVIDER_OPTIONS: Array<{ value: LlmProvider; label: string; defaultModel: string }> = [
  { value: "openai", label: "OpenAI", defaultModel: "gpt-4.1-mini" },
  { value: "anthropic", label: "Anthropic", defaultModel: "claude-sonnet-4-5" },
  { value: "gemini", label: "Google Gemini", defaultModel: "gemini-2.5-flash" },
  { value: "azure-openai", label: "Azure OpenAI", defaultModel: "my-gpt-4o-deployment" },
  { value: "ollama", label: "Ollama (local)", defaultModel: "llama3.2" },
  { value: "openai-compatible", label: "OpenAI-compatible (vLLM, LM Studio, OpenRouter...)", defaultModel: "local-model" }
];

export interface GeneratedConfig {
  install: string;
  env: string;
  code: { language: string; fileName: string; content: string };
  notes: string[];
}

const q = (value: string) => JSON.stringify(value);

function envFor(provider: LlmProvider, baseUrl?: string): Array<[string, string, string]> {
  switch (provider) {
    case "openai": return [["OPENAI_API_KEY", "sk-...", "https://platform.openai.com/api-keys"]];
    case "anthropic": return [["ANTHROPIC_API_KEY", "sk-ant-...", "https://console.anthropic.com/settings/keys"]];
    case "gemini": return [["GEMINI_API_KEY", "...", "https://aistudio.google.com/apikey"]];
    case "azure-openai": return [
      ["AZURE_OPENAI_API_KEY", "...", "Azure portal > your OpenAI resource > Keys and Endpoint"],
      ["AZURE_OPENAI_ENDPOINT", "https://<resource>.openai.azure.com", "Azure portal > Keys and Endpoint"],
      ["AZURE_OPENAI_API_VERSION", "2024-10-21", "API version"]
    ];
    case "ollama": return [["OLLAMA_BASE_URL", baseUrl || "http://localhost:11434/v1", "Local Ollama server (no key needed)"]];
    default: return [
      ["LLM_BASE_URL", baseUrl || "http://localhost:8000/v1", "Your OpenAI-compatible server"],
      ["LLM_API_KEY", "change-me", "Leave any value if the server does not check keys"]
    ];
  }
}

function pythonCode(o: LlmConfigOptions): string {
  const header = `"""LLM client setup generated by DevSnip Pro. Keys come from the environment (.env)."""\nimport os\n`;
  const prompt = `SYSTEM_PROMPT = "You are a helpful assistant."\nUSER_PROMPT = "Explain retrieval-augmented generation in two sentences."\n`;
  switch (o.provider) {
    case "anthropic":
      return `${header}\nimport anthropic\n\nclient = anthropic.Anthropic(\n    api_key=os.environ["ANTHROPIC_API_KEY"],\n    timeout=${o.timeoutSeconds},\n    max_retries=${o.maxRetries},\n)\n\n${prompt}\n\ndef main() -> None:\n${o.stream
        ? `    with client.messages.stream(\n        model=${q(o.model)},\n        max_tokens=1024,\n        temperature=${o.temperature},\n        system=SYSTEM_PROMPT,\n        messages=[{"role": "user", "content": USER_PROMPT}],\n    ) as stream:\n        for text in stream.text_stream:\n            print(text, end="", flush=True)\n    print()\n`
        : `    message = client.messages.create(\n        model=${q(o.model)},\n        max_tokens=1024,\n        temperature=${o.temperature},\n        system=SYSTEM_PROMPT,\n        messages=[{"role": "user", "content": USER_PROMPT}],\n    )\n    print("".join(block.text for block in message.content if block.type == "text"))\n    print(f"tokens: {message.usage.input_tokens} in / {message.usage.output_tokens} out")\n`}\n\nif __name__ == "__main__":\n    main()\n`;
    case "gemini":
      return `${header}\nfrom google import genai\nfrom google.genai import types\n\nclient = genai.Client(\n    api_key=os.environ["GEMINI_API_KEY"],\n    http_options=types.HttpOptions(timeout=${o.timeoutSeconds * 1000}),\n)\n\n${prompt}\nCONFIG = types.GenerateContentConfig(system_instruction=SYSTEM_PROMPT, temperature=${o.temperature})\n\n\ndef main() -> None:\n${o.stream
        ? `    for chunk in client.models.generate_content_stream(model=${q(o.model)}, contents=USER_PROMPT, config=CONFIG):\n        print(chunk.text or "", end="", flush=True)\n    print()\n`
        : `    response = client.models.generate_content(model=${q(o.model)}, contents=USER_PROMPT, config=CONFIG)\n    print(response.text)\n`}\n\nif __name__ == "__main__":\n    main()\n`;
    default: {
      const construct = o.provider === "azure-openai"
        ? `from openai import AzureOpenAI\n\nclient = AzureOpenAI(\n    api_key=os.environ["AZURE_OPENAI_API_KEY"],\n    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],\n    api_version=os.environ.get("AZURE_OPENAI_API_VERSION", "2024-10-21"),\n    timeout=${o.timeoutSeconds},\n    max_retries=${o.maxRetries},\n)\n# For Azure, "model" is your deployment name.`
        : o.provider === "ollama"
          ? `from openai import OpenAI\n\nclient = OpenAI(\n    base_url=os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434/v1"),\n    api_key="ollama",  # required by the SDK, ignored by Ollama\n    timeout=${o.timeoutSeconds},\n    max_retries=${o.maxRetries},\n)`
          : o.provider === "openai-compatible"
            ? `from openai import OpenAI\n\nclient = OpenAI(\n    base_url=os.environ["LLM_BASE_URL"],\n    api_key=os.environ.get("LLM_API_KEY", "not-needed"),\n    timeout=${o.timeoutSeconds},\n    max_retries=${o.maxRetries},\n)`
            : `from openai import OpenAI\n\nclient = OpenAI(\n    api_key=os.environ["OPENAI_API_KEY"],\n    timeout=${o.timeoutSeconds},\n    max_retries=${o.maxRetries},\n)`;
      const messages = `        messages=[\n            {"role": "system", "content": SYSTEM_PROMPT},\n            {"role": "user", "content": USER_PROMPT},\n        ],`;
      return `${header}\n${construct}\n\n${prompt}\n\ndef main() -> None:\n${o.stream
        ? `    stream = client.chat.completions.create(\n        model=${q(o.model)},\n${messages}\n        temperature=${o.temperature},\n        stream=True,\n    )\n    for chunk in stream:\n        if chunk.choices and chunk.choices[0].delta.content:\n            print(chunk.choices[0].delta.content, end="", flush=True)\n    print()\n`
        : `    response = client.chat.completions.create(\n        model=${q(o.model)},\n${messages}\n        temperature=${o.temperature},\n    )\n    print(response.choices[0].message.content)\n    if response.usage:\n        print(f"tokens: {response.usage.prompt_tokens} in / {response.usage.completion_tokens} out")\n`}\n\nif __name__ == "__main__":\n    main()\n`;
    }
  }
}

function typescriptCode(o: LlmConfigOptions): string {
  const header = `// LLM client setup generated by DevSnip Pro. Keys come from the environment (.env).\n`;
  const prompt = `const SYSTEM_PROMPT = "You are a helpful assistant.";\nconst USER_PROMPT = "Explain retrieval-augmented generation in two sentences.";\n`;
  const footer = `\nmain().catch(error => {\n  console.error(error);\n  process.exitCode = 1;\n});\n`;
  switch (o.provider) {
    case "anthropic":
      return `${header}import Anthropic from "@anthropic-ai/sdk";\n\nconst client = new Anthropic({\n  apiKey: process.env.ANTHROPIC_API_KEY,\n  timeout: ${o.timeoutSeconds * 1000},\n  maxRetries: ${o.maxRetries},\n});\n\n${prompt}\nasync function main(): Promise<void> {\n${o.stream
        ? `  const stream = client.messages.stream({\n    model: ${q(o.model)},\n    max_tokens: 1024,\n    temperature: ${o.temperature},\n    system: SYSTEM_PROMPT,\n    messages: [{ role: "user", content: USER_PROMPT }],\n  });\n  stream.on("text", text => process.stdout.write(text));\n  await stream.finalMessage();\n  process.stdout.write("\\n");\n`
        : `  const message = await client.messages.create({\n    model: ${q(o.model)},\n    max_tokens: 1024,\n    temperature: ${o.temperature},\n    system: SYSTEM_PROMPT,\n    messages: [{ role: "user", content: USER_PROMPT }],\n  });\n  for (const block of message.content) {\n    if (block.type === "text") console.log(block.text);\n  }\n  console.log(\`tokens: \${message.usage.input_tokens} in / \${message.usage.output_tokens} out\`);\n`}}\n${footer}`;
    case "gemini":
      return `${header}import { GoogleGenAI } from "@google/genai";\n\nconst ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY, httpOptions: { timeout: ${o.timeoutSeconds * 1000} } });\n\n${prompt}\nasync function main(): Promise<void> {\n  const request = {\n    model: ${q(o.model)},\n    contents: USER_PROMPT,\n    config: { systemInstruction: SYSTEM_PROMPT, temperature: ${o.temperature} },\n  };\n${o.stream
        ? `  for await (const chunk of await ai.models.generateContentStream(request)) {\n    process.stdout.write(chunk.text ?? "");\n  }\n  process.stdout.write("\\n");\n`
        : `  const response = await ai.models.generateContent(request);\n  console.log(response.text);\n`}}\n${footer}`;
    default: {
      const construct = o.provider === "azure-openai"
        ? `import { AzureOpenAI } from "openai";\n\n// For Azure, "model" is your deployment name.\nconst client = new AzureOpenAI({\n  apiKey: process.env.AZURE_OPENAI_API_KEY,\n  endpoint: process.env.AZURE_OPENAI_ENDPOINT,\n  apiVersion: process.env.AZURE_OPENAI_API_VERSION ?? "2024-10-21",\n  timeout: ${o.timeoutSeconds * 1000},\n  maxRetries: ${o.maxRetries},\n});`
        : o.provider === "ollama"
          ? `import OpenAI from "openai";\n\nconst client = new OpenAI({\n  baseURL: process.env.OLLAMA_BASE_URL ?? "http://localhost:11434/v1",\n  apiKey: "ollama", // required by the SDK, ignored by Ollama\n  timeout: ${o.timeoutSeconds * 1000},\n  maxRetries: ${o.maxRetries},\n});`
          : o.provider === "openai-compatible"
            ? `import OpenAI from "openai";\n\nconst client = new OpenAI({\n  baseURL: process.env.LLM_BASE_URL,\n  apiKey: process.env.LLM_API_KEY ?? "not-needed",\n  timeout: ${o.timeoutSeconds * 1000},\n  maxRetries: ${o.maxRetries},\n});`
            : `import OpenAI from "openai";\n\nconst client = new OpenAI({\n  apiKey: process.env.OPENAI_API_KEY,\n  timeout: ${o.timeoutSeconds * 1000},\n  maxRetries: ${o.maxRetries},\n});`;
      const messages = `    messages: [\n      { role: "system", content: SYSTEM_PROMPT },\n      { role: "user", content: USER_PROMPT },\n    ],`;
      return `${header}${construct}\n\n${prompt}\nasync function main(): Promise<void> {\n${o.stream
        ? `  const stream = await client.chat.completions.create({\n    model: ${q(o.model)},\n${messages}\n    temperature: ${o.temperature},\n    stream: true,\n  });\n  for await (const chunk of stream) {\n    process.stdout.write(chunk.choices[0]?.delta?.content ?? "");\n  }\n  process.stdout.write("\\n");\n`
        : `  const response = await client.chat.completions.create({\n    model: ${q(o.model)},\n${messages}\n    temperature: ${o.temperature},\n  });\n  console.log(response.choices[0]?.message.content);\n  if (response.usage) console.log(\`tokens: \${response.usage.prompt_tokens} in / \${response.usage.completion_tokens} out\`);\n`}}\n${footer}`;
    }
  }
}

function curlCode(o: LlmConfigOptions): string {
  const stream = o.stream ? "true" : "false";
  switch (o.provider) {
    case "anthropic":
      return `#!/usr/bin/env sh\n# Requires ANTHROPIC_API_KEY in the environment.\ncurl --fail-with-body --max-time ${o.timeoutSeconds} https://api.anthropic.com/v1/messages \\\n  -H "x-api-key: $ANTHROPIC_API_KEY" \\\n  -H "anthropic-version: 2023-06-01" \\\n  -H "content-type: application/json" \\\n  -d '${JSON.stringify({ model: o.model, max_tokens: 1024, temperature: o.temperature, stream: o.stream, system: "You are a helpful assistant.", messages: [{ role: "user", content: "Explain retrieval-augmented generation in two sentences." }] })}'\n`;
    case "gemini":
      return `#!/usr/bin/env sh\n# Requires GEMINI_API_KEY in the environment.\ncurl --fail-with-body --max-time ${o.timeoutSeconds} "https://generativelanguage.googleapis.com/v1beta/models/${o.model}:${o.stream ? "streamGenerateContent?alt=sse" : "generateContent"}" \\\n  -H "x-goog-api-key: $GEMINI_API_KEY" \\\n  -H "content-type: application/json" \\\n  -d '${JSON.stringify({ systemInstruction: { parts: [{ text: "You are a helpful assistant." }] }, contents: [{ role: "user", parts: [{ text: "Explain retrieval-augmented generation in two sentences." }] }], generationConfig: { temperature: o.temperature } })}'\n`;
    default: {
      const url = o.provider === "azure-openai"
        ? `"$AZURE_OPENAI_ENDPOINT/openai/deployments/${o.model}/chat/completions?api-version=$AZURE_OPENAI_API_VERSION"`
        : o.provider === "ollama" ? `"\${OLLAMA_BASE_URL:-http://localhost:11434/v1}/chat/completions"`
          : o.provider === "openai-compatible" ? `"$LLM_BASE_URL/chat/completions"` : "https://api.openai.com/v1/chat/completions";
      const auth = o.provider === "azure-openai" ? `-H "api-key: $AZURE_OPENAI_API_KEY"`
        : o.provider === "ollama" ? "" : o.provider === "openai-compatible" ? `-H "Authorization: Bearer $LLM_API_KEY"` : `-H "Authorization: Bearer $OPENAI_API_KEY"`;
      return `#!/usr/bin/env sh\ncurl --fail-with-body --max-time ${o.timeoutSeconds} ${url} \\\n  -H "content-type: application/json" \\\n${auth ? `  ${auth} \\\n` : ""}  -d '${JSON.stringify({ model: o.model, temperature: o.temperature, stream: stream === "true", messages: [{ role: "system", content: "You are a helpful assistant." }, { role: "user", content: "Explain retrieval-augmented generation in two sentences." }] })}'\n`;
    }
  }
}

export function generateLlmConfig(o: LlmConfigOptions): GeneratedConfig {
  const env = envFor(o.provider, o.baseUrl);
  const envText = `# ${LLM_PROVIDER_OPTIONS.find(p => p.value === o.provider)?.label} settings. Copy to .env and keep .env out of git.\n${env.map(([name, example, where]) => `# ${where}\n${name}=${example}`).join("\n")}\n`;
  const pythonPackage = o.provider === "anthropic" ? "anthropic" : o.provider === "gemini" ? "google-genai" : "openai";
  const nodePackage = o.provider === "anthropic" ? "@anthropic-ai/sdk" : o.provider === "gemini" ? "@google/genai" : "openai";
  const install = o.language === "python" ? `pip install ${pythonPackage} python-dotenv` : o.language === "typescript" ? `npm install ${nodePackage} dotenv` : "# curl only - nothing to install";
  const code = o.language === "python"
    ? { language: "python", fileName: "llm_client.py", content: pythonCode(o) }
    : o.language === "typescript"
      ? { language: "typescript", fileName: "llmClient.ts", content: typescriptCode(o) }
      : { language: "shellscript", fileName: "llm-request.sh", content: curlCode(o) };
  const notes = [
    "The API key is read from the environment. Load .env with python-dotenv / dotenv (or your platform's secret store) and never commit it.",
    `Timeout ${o.timeoutSeconds}s and ${o.maxRetries} automatic retries with backoff (SDKs retry 408, 429 and 5xx).`,
    "Call the API from a server, never from browser code: a key shipped to a browser is public."
  ];
  if (o.provider === "ollama") notes.push("Start the model first: ollama pull " + o.model + " && ollama serve");
  if (o.provider === "azure-openai") notes.push("\"model\" is the deployment name you created in Azure, not the base model name.");
  if (/^(gpt-5|o\d)/.test(o.model) && o.temperature !== 1) notes.push("OpenAI reasoning models (gpt-5, o-series) only accept the default temperature; remove it if the API rejects the request.");
  return { install, env: envText, code, notes };
}
